Prog: main.o GestionPort.o Voilier.o Usager.o
	g++ -o prog main.o GestionPort.o Voilier.o Usager.o

GestionPort.o: GestionPort.cpp GestionPort.h
	g++ -c GestionPort.cpp

Voilier.o: Voilier.cpp Voilier.h
	g++ -c Voilier.cpp

Usager.o: Usager.cpp Usager.h Voilier.h
	g++ -c Usager.cpp